# Generated by Django 6.0.2 on 2026-02-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text='Процент скидки'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'Очень маленький'), ('S', 'Маленький'), ('M', 'Средний'), ('L', 'Большой'), ('XL', 'Очень большой'), ('XXL', 'Огромный размер')], default='M', max_length=3),
        ),
    ]
